package com.metatron.model;

// default package
// Generated 25/06/2019 20:55:54 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", catalog = "teste")
public class Cargo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2209798288729389644L;
	private Integer id;
	private String nome;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Cargo() {
	}

	public Cargo(String nome) {
		this.nome = nome;
	}

	public Cargo(String nome, Set<Usuario> usuarios) {
		this.nome = nome;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
