package com.metatron.model;

// default package
// Generated 25/06/2019 20:55:54 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name = "telefone", catalog = "teste")
public class Telefone implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2757484084510328764L;
	private Integer id;
	private Usuario usuario;
	private int ddd;
	private int numero;

	public Telefone() {
	}

	public Telefone(int ddd, int numero) {
		this.ddd = ddd;
		this.numero = numero;
	}

	public Telefone(Usuario usuario, int ddd, int numero) {
		this.usuario = usuario;
		this.ddd = ddd;
		this.numero = numero;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ddd", nullable = false)
	public int getDdd() {
		return this.ddd;
	}

	public void setDdd(int ddd) {
		this.ddd = ddd;
	}

	@Column(name = "numero", nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
